### PR TITLE
conscience-agent: check for service endpoint conflicts

### PR DESCRIPTION
**Pull request by fvennetier**
##### SUMMARY
If several services are configured on the same endpoint, log an error,
and do not report them to the conscience.

Jira: OBSTO-192

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
- conscience-agent

##### SDS VERSION
```
openio 7.1.1.dev2
```

### CODE REVIEW

**Review by AymericDu — APPROVED** [review]

**Comment by cdelgehier** [comment]
So first come, first served ? 
I didn't see any unregister action, so is it a "first come, first served" ?

**Comment by fvennetier** [comment]
> So first come, first served ?
> I didn't see any unregister action, so is it a "first come, first served" ?

That's right, I did not put any unregister action. None of the conflicting services will be updated. But I can change that, and register one of them. Notice though that the code cannot identify which one is the good one...

**Comment by fatpat** [comment]
would it be possible to lock them with a 0 score ?

**Comment by fvennetier** [comment]
> would it be possible to lock them with a 0 score ?

It is possible. But the problem is that "locking" them means registering them. If a faulty service is "locked", it will appear in the conscience until it is garbage collected. With this pre-registration check, it won't be registered at all.

**Review by murlock — APPROVED** [review]

**Review by fatpat — APPROVED** [review]

**Pull request merged**
